name: YAPF Formatting Check
on: [push]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: run YAPF to test if python code is correctly formatted.
      uses: ingomueller-net/yapf-action@working-dir
      with:
        args: --verbose --exclude 'test/**' --exclude '**/invalid_file.py'
